### ISSUE TITLE
Use in Word documents

### ISSUE THREAD

**Issue by JamesDavidAudlin** [yehuthi/koseva#1]
Greetings from Panama: I am a retired professor and scholar of early Biblical texts. As such, while I am not sure, your "Koseva" may be of use to me. I write for publication in Microsoft Word documents, and at times need to reproduce in the documents representations of my transcriptions of very early texts. Now, please understand - I know absolutely nothing about programming and so on. Just to ask this question required me to set up a GitHub account which I doubt I will ever use again. I simply need to know whether, if I install your Koseva program, I can use it to reproduce palaeo-Hebrew and palaeo-Aramaic texts in something resembling the original alphabet. If it is easier for you (certainly it is for me), you are welcome to reply to me at my e-address ---> jaudlin@gmail.com <--- and thank you, todah! --James David Audlin

**Comment by yehuthi** [comment]
Hey @JamesDavidAudlin, apologies for my very late response.

Could you elaborate on what you mean "reproduce" texts? If you mean convert Hebrew text into Paleo-Hebrew, I have a different project that's dedicated to conversions in general, it's work-in-progress at the moment, but conversion from Hebrew to Paleo-Hebrew is already implemented, and you can use it here: https://yehuthi.github.io/tatqan/
I'm not sure what you mean about Paleo-Aramaic, if you're referring to very early Aramaic writings then I would _guess_ the Paleo-Hebrew / Phoenician script would have been used for that as well in that case (and you would probably know better), you can use the tool above as well. Otherwise, feel free to give more details, I'd love to help.

**Comment by JamesDavidAudlin** [comment]
Greetings! I don't know if your name is Yehuthi or Koseva or both or
neither, so forgive me for not greeting you properly!

Thank you very much for your kind reply; forgive me as well for not
remembering even writing to you - evidently it was quite some time ago. My
original message seems to have disappeared out of my gmail memory.

For the book, I do need occasionally to reproduce original texts in
transcription with the palaeo-Hebrew or palaeo-Aramaic alphabets. I'll play
with your conversion program and see what results it gives me. Thank you
for that!

all best wishes from rural Panama,

James David Audlin
